machine:
  environment:
    IMAGE: dragonfly_libvips_$CIRCLE_BRANCH
    TAG: $CIRCLE_SHA1

  services:
    - docker

dependencies:
  cache_directories:
    - "~/docker"

  override:
    - if [[ -e ~/docker/image_$CIRCLE_BRANCH.tar ]]; then docker load -i ~/docker/image_$CIRCLE_BRANCH.tar; fi

    - docker build -t $IMAGE:$TAG .
    - docker tag $IMAGE:$TAG $IMAGE:latest

    - mkdir -p ~/docker; docker save $DOCKER_USER/$IMAGE:$TAG > ~/docker/image_$CIRCLE_BRANCH.tar

test:
  override:
    - docker run $IMAGE:$TAG bundle exec rake
