sudo: false
language: ruby
script: 'bundle exec rake'
sudo: required
rvm:
  - 2.2.5
before_install:
  - gem install bundler -v 1.12.5
  - sudo apt-get update
  - sudo apt-get install -y libvips
notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
