# libvips build instructions taken from https://github.com/marcbachmann/dockerfile-libvips

language: ruby
script: 'bundle exec rake'
sudo: required
dist: trusty
rvm:
  - 2.2.5
env:
  - LIBVIPS_VERSION_MAJOR=8 LIBVIPS_VERSION_MINOR=3 LIBVIPS_VERSION_PATCH=3 LIBVIPS_VERSION=$LIBVIPS_VERSION_MAJOR.$LIBVIPS_VERSION_MINOR.$LIBVIPS_VERSION_PATCH
before_install:
  - gem install bundler -v 1.12.5
  - curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
