# libvips build instructions taken from https://github.com/marcbachmann/dockerfile-libvips

language: ruby
script: 'bundle exec rake'
sudo: required
dist: trusty
rvm:
  - 2.2.5
before_install:
  - gem install bundler -v 1.12.5
  - npm install sharp

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
